name: CI PyAudit
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Installation
        run: pip install -e . && pip install pytest pytest-cov bandit
      - name: Audit statique
        run: bandit -r pyaudit/ -ll
      - name: Tests
        run: pytest tests/ --cov=pyaudit --cov-report=term-missing
